services:
  _defaults:
    autowire: true

  D3\LoggerExtension\LoggerFactoryExtension:
    class: D3\LoggerExtension\LoggerFactoryExtension
    decorates: OxidEsales\EshopCommunity\Internal\Framework\Logger\Factory\LoggerFactoryInterface
    decoration_inner_name: 'oxid.d3_loggerfactory.inner'
    arguments:
      - '@oxid.d3_loggerfactory.inner'