services:
  _defaults:
    autowire: true

  D3\LoggerExtension\ConfigurationExtension:
    class: D3\LoggerExtension\ConfigurationExtension
    decorates: OxidEsales\EshopCommunity\Internal\Framework\Logger\Configuration\MonologConfigurationInterface
    decoration_inner_name: 'oxid.d3_loggerconfuguration.inner'
    arguments:
      - '@oxid.d3_loggerconfiguration.inner'